//! System tray icon: connection-status icon/tooltip and the show/hide
//! settings menu item.

use std::sync::OnceLock;

use tauri::image::Image;
use tauri::{
    menu::{MenuBuilder, MenuItem},
    tray::TrayIconBuilder,
};
use tauri::{AppHandle, Emitter, Manager};
use tracing::warn;

use super::{SharedStatus, StoredConfig};
use crate::config::AgentStatus;

static TRAY_ICONS: OnceLock<TrayIcons> = OnceLock::new();
static TRAY_TOGGLE_ITEM: OnceLock<MenuItem<tauri::Wry>> = OnceLock::new();
#[derive(Clone)]
struct TrayIcons {
    ok: Image<'static>,
    bad: Image<'static>,
    busy: Image<'static>,
}
const TRAY_ID: &str = "vantyr-agent-tray";
fn truncate_one_line(s: &str, max_chars: usize) -> String {
    let mut out = String::with_capacity(s.len().min(max_chars));
    for ch in s.chars() {
        if ch == '\r' || ch == '\n' {
            break;
        }
        out.push(ch);
        if out.chars().count() >= max_chars {
            out.push('…');
            break;
        }
    }
    out
}
fn status_to_tray_payload(status: &AgentStatus) -> (String, &'static str) {
    match status {
        AgentStatus::Connected => ("Vantyr Agent — Connected".into(), "ok"),
        AgentStatus::Connecting => ("Vantyr Agent — Connecting…".into(), "busy"),
        AgentStatus::Disconnected => ("Vantyr Agent — Disconnected".into(), "bad"),
        AgentStatus::Error(msg) => (
            format!("Vantyr Agent — Error: {}", truncate_one_line(msg, 120)),
            "bad",
        ),
    }
}
fn build_tray_icons() -> Result<TrayIcons, String> {
    // Pre-rendered assets generated by `agent/tools/gen_tray_icons.py`.
    const OK: &[u8] = include_bytes!("../../icons/tray_ok.png");
    const BAD: &[u8] = include_bytes!("../../icons/tray_bad.png");
    const BUSY: &[u8] = include_bytes!("../../icons/tray_busy.png");

    Ok(TrayIcons {
        ok: Image::from_bytes(OK).map_err(|e| e.to_string())?,
        bad: Image::from_bytes(BAD).map_err(|e| e.to_string())?,
        busy: Image::from_bytes(BUSY).map_err(|e| e.to_string())?,
    })
}
fn show_settings_window(handle: AppHandle) {
    // Creating a window in an event handler can deadlock on Windows (WebView2).
    // Keep the same safe pattern as the global shortcut handler.
    std::thread::spawn(move || {
        if let Some(w) = handle.get_webview_window("main") {
            let _ = w.show();
            let _ = w.set_focus();
            return;
        }

        let cfg = handle
            .config()
            .app
            .windows
            .iter()
            .find(|w| w.label == "main")
            .or_else(|| handle.config().app.windows.first())
            .cloned();
        let Some(conf) = cfg else { return };
        let _ = tauri::WebviewWindowBuilder::from_config(&handle, &conf)
            .and_then(tauri::WebviewWindowBuilder::build);
        if let Some(w) = handle.get_webview_window("main") {
            let _ = w.show();
            let _ = w.set_focus();
        }
    });
}
fn hide_settings_window(handle: &AppHandle) {
    if let Some(win) = handle.get_webview_window("main") {
        let _ = win.emit("lock_ui", ());
        let _ = win.destroy();
    }
}
fn settings_window_visible(app: &AppHandle) -> bool {
    app.get_webview_window("main")
        .and_then(|w| w.is_visible().ok())
        .unwrap_or(false)
}
fn set_toggle_label(app: &AppHandle) {
    let label = if settings_window_visible(app) {
        "Hide Agent Settings"
    } else {
        "Show Agent Settings"
    };
    if let Some(item) = TRAY_TOGGLE_ITEM.get() {
        let _ = item.set_text(label);
    }
}
fn install_tray(handle: AppHandle) -> Result<(), String> {
    let icons = TRAY_ICONS
        .get()
        .cloned()
        .ok_or_else(|| "tray icons not initialised".to_string())?;

    let initial_toggle_label = if settings_window_visible(&handle) {
        "Hide Agent Settings"
    } else {
        "Show Agent Settings"
    };
    let toggle_i = MenuItem::with_id(
        &handle,
        "toggle_settings",
        initial_toggle_label,
        true,
        None::<&str>,
    )
    .map_err(|e| e.to_string())?;
    let _ = TRAY_TOGGLE_ITEM.set(toggle_i.clone());

    let menu = MenuBuilder::new(&handle)
        .item(&toggle_i)
        .build()
        .map_err(|e| e.to_string())?;

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(icons.bad.clone())
        .tooltip("Vantyr Agent — Disconnected")
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(move |app, event| {
            if event.id().as_ref() == "toggle_settings" {
                if settings_window_visible(app) {
                    hide_settings_window(app);
                } else {
                    show_settings_window(app.clone());
                }
                set_toggle_label(app);
            }
        })
        .build(&handle)
        .map_err(|e| e.to_string())?;

    Ok(())
}
pub(super) fn ensure_tray_matches_config(app: &AppHandle) {
    let enabled = app
        .state::<StoredConfig>()
        .0
        .lock()
        .map(|c| c.tray_icon_enabled)
        .unwrap_or(true);

    if enabled {
        if app.tray_by_id(TRAY_ID).is_none() {
            if let Err(e) = install_tray(app.clone()) {
                warn!("Failed to install tray icon: {e}");
            }
        } else if let Some(tray) = app.tray_by_id(TRAY_ID) {
            let _ = tray.set_visible(true);
        }
        set_toggle_label(app);
    } else if let Some(tray) = app.tray_by_id(TRAY_ID) {
        let _ = tray.set_visible(false);
    }
}
fn start_tray_status_watcher(app: AppHandle) {
    // Efficiency: poll at a low frequency and only update when status changes.
    // Agent connection state changes relatively rarely, so this is effectively idle.
    tauri::async_runtime::spawn(async move {
        use tokio::time::{sleep, Duration};

        let mut last_status = AgentStatus::Disconnected;
        let mut last_tooltip = String::new();
        let mut last_kind = "";
        let mut last_visible = settings_window_visible(&app);
        let mut last_tray_enabled = app
            .state::<StoredConfig>()
            .0
            .lock()
            .map(|c| c.tray_icon_enabled)
            .unwrap_or(true);

        loop {
            let tray_enabled = app
                .state::<StoredConfig>()
                .0
                .lock()
                .map(|c| c.tray_icon_enabled)
                .unwrap_or(true);

            if tray_enabled != last_tray_enabled {
                ensure_tray_matches_config(&app);
                last_tray_enabled = tray_enabled;
            }

            let status = app
                .state::<SharedStatus>()
                .0
                .lock()
                .map(|s| s.clone())
                .unwrap_or(AgentStatus::Error("status lock poisoned".into()));

            let visible_now = settings_window_visible(&app);
            if visible_now != last_visible {
                set_toggle_label(&app);
                last_visible = visible_now;
            }

            if status != last_status {
                let (tooltip, kind) = status_to_tray_payload(&status);

                // Update tooltip.
                if tooltip != last_tooltip {
                    if let Some(tray) = app.tray_by_id(TRAY_ID) {
                        let _ = tray.set_tooltip(Some(tooltip.clone()));
                    }
                    last_tooltip = tooltip;
                }

                // Update icon only when the "kind" changes.
                if kind != last_kind {
                    if let Some(tray) = app.tray_by_id(TRAY_ID) {
                        let icons = TRAY_ICONS.get().cloned();
                        if let Some(icons) = icons {
                            let icon = match kind {
                                "ok" => icons.ok,
                                "busy" => icons.busy,
                                _ => icons.bad,
                            };
                            let _ = tray.set_icon(Some(icon));
                        }
                    }
                    last_kind = kind;
                }

                last_status = status;
            }

            sleep(Duration::from_millis(900)).await;
        }
    });
}

/// Precompute the icons, install the tray if enabled and start the status
/// watcher. Called once from the Tauri setup hook.
pub(super) fn setup(app: &AppHandle) {
    // Precompute tray icons once (cheap and avoids any runtime decoding on updates).
    if TRAY_ICONS.get().is_none() {
        match build_tray_icons() {
            Ok(i) => {
                let _ = TRAY_ICONS.set(i);
            }
            Err(e) => {
                warn!("Failed to build tray icons: {e}");
            }
        }
    }

    // Install the tray if enabled. Even if it fails, keep the agent functional.
    let enabled = app
        .state::<StoredConfig>()
        .0
        .lock()
        .map(|c| c.tray_icon_enabled)
        .unwrap_or(true);
    if enabled {
        if let Err(e) = install_tray(app.clone()) {
            warn!("Failed to install tray icon: {e}");
        }
    }
    start_tray_status_watcher(app.clone());
}
