import { baseConfig } from "@vantyr/eslint-config";

export default [
  ...baseConfig({ reactCompilerRules: true }),
  // Generated by ts-rs from the server's Rust structs (see server/docs/ARCHITECTURE.md).
  { ignores: ["src/api/types/generated"] },
  {
    // ErrorBoundary is a class component, which Fast Refresh can't preserve anyway.
    files: ["src/components/common/ErrorBoundary.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
];
