//! Tauri-based settings window for the Sentinel agent.
//!
//! ## Architecture
//!
//! Tauri owns the main thread and its webview event loop.  The agent's
//! background Tokio runtime continues to run in a separate OS thread (spawned
//! by `main` before this module is called).
//!
//! Shared state is passed into the Tauri app via `.manage()`:
//! - `SharedConfig`  – `Arc<tokio::sync::watch::Sender<Option<Config>>>`
//! - `SharedStatus`  – `Arc<Mutex<AgentStatus>>`
//! - `StoredConfig`  – `Arc<Mutex<Config>>` (latest saved config, for reads)
//!
//! ## IPC Commands (webview → Rust)
//!
//! | Command              | Returns                  | Description                          |
//! |----------------------|--------------------------|--------------------------------------|
//! | `get_config`         | `Config` JSON            | Read current config                  |
//! | `save_config`        | `()`                     | Persist + hot-reload config          |
//! | `get_status`         | `StatusResponse` JSON    | Current WS connection status         |
//! | `has_ui_password`    | `bool`                   | Whether a UI password is set         |
//! | `verify_ui_password` | `()` or Err              | Check UI password                    |
//! | `hide_window`        | `()`                     | Hide the settings window             |
//! | `exit_agent`         | never                    | Kill the process                     |
//! | `check_manual_update`| `ManualUpdateCheckResponse` | Compare build to `latest.json` (Windows) |
//! | `apply_manual_update`| `ManualApplyUpdateResponse` | Download + service `msiexec` (Windows) |
//! | `list_log_sources`   | `Vec<LogSourceDesc>`     | Known on-disk log files for the Logs tab   |
//! | `read_log_file_tail` | `String`                 | Tail of a log file (see `kind` + `max_kb`) |
//! | `clear_log_file`     | `()`                     | Truncate a log file to zero bytes          |
//! | `open_log_location`  | `()`                     | Open the log file in Explorer (Windows)    |

use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::OnceLock;
use std::sync::{Arc, Mutex};

use argon2::{Argon2, PasswordHash, PasswordVerifier};

use tauri::image::Image;
use tauri::{
    menu::{MenuBuilder, MenuItem},
    tray::TrayIconBuilder,
};
use tauri::{AppHandle, Emitter, Manager, State};
use tauri_plugin_global_shortcut::{Code, GlobalShortcutExt, Modifiers, Shortcut, ShortcutState};
#[cfg(not(target_os = "windows"))]
use tauri_plugin_updater::UpdaterExt;
use tracing::{error, info, warn};

use crate::config::{AgentStatus, Config};

static APP_HANDLE: OnceLock<AppHandle> = OnceLock::new();
static LAST_UI_AUTH_OK_AT: OnceLock<AtomicI64> = OnceLock::new();

static TRAY_ICONS: OnceLock<TrayIcons> = OnceLock::new();
static TRAY_TOGGLE_ITEM: OnceLock<MenuItem<tauri::Wry>> = OnceLock::new();

#[derive(Clone)]
struct TrayIcons {
    ok: Image<'static>,
    bad: Image<'static>,
    busy: Image<'static>,
}

const TRAY_ID: &str = "sentinel-agent-tray";

fn truncate_one_line(s: &str, max_chars: usize) -> String {
    let mut out = String::with_capacity(s.len().min(max_chars));
    for ch in s.chars() {
        if ch == '\r' || ch == '\n' {
            break;
        }
        out.push(ch);
        if out.chars().count() >= max_chars {
            out.push('…');
            break;
        }
    }
    out
}

fn status_to_tray_payload(status: &AgentStatus) -> (String, &'static str) {
    match status {
        AgentStatus::Connected => ("Sentinel Agent — Connected".into(), "ok"),
        AgentStatus::Connecting => ("Sentinel Agent — Connecting…".into(), "busy"),
        AgentStatus::Disconnected => ("Sentinel Agent — Disconnected".into(), "bad"),
        AgentStatus::Error(msg) => (
            format!("Sentinel Agent — Error: {}", truncate_one_line(msg, 120)),
            "bad",
        ),
    }
}

fn build_tray_icons() -> Result<TrayIcons, String> {
    // Pre-rendered assets generated by `agent/tools/gen_tray_icons.py`.
    const OK: &[u8] = include_bytes!("../icons/tray_ok.png");
    const BAD: &[u8] = include_bytes!("../icons/tray_bad.png");
    const BUSY: &[u8] = include_bytes!("../icons/tray_busy.png");

    Ok(TrayIcons {
        ok: Image::from_bytes(OK).map_err(|e| e.to_string())?,
        bad: Image::from_bytes(BAD).map_err(|e| e.to_string())?,
        busy: Image::from_bytes(BUSY).map_err(|e| e.to_string())?,
    })
}

fn show_settings_window(handle: AppHandle) {
    // Creating a window in an event handler can deadlock on Windows (WebView2).
    // Keep the same safe pattern as the global shortcut handler.
    std::thread::spawn(move || {
        if let Some(w) = handle.get_webview_window("main") {
            let _ = w.show();
            let _ = w.set_focus();
            return;
        }

        let cfg = handle
            .config()
            .app
            .windows
            .iter()
            .find(|w| w.label == "main")
            .or_else(|| handle.config().app.windows.first())
            .cloned();
        let Some(conf) = cfg else { return };
        let _ = tauri::WebviewWindowBuilder::from_config(&handle, &conf)
            .and_then(tauri::WebviewWindowBuilder::build);
        if let Some(w) = handle.get_webview_window("main") {
            let _ = w.show();
            let _ = w.set_focus();
        }
    });
}

fn hide_settings_window(handle: &AppHandle) {
    if let Some(win) = handle.get_webview_window("main") {
        let _ = win.emit("lock_ui", ());
        let _ = win.destroy();
    }
}

fn settings_window_visible(app: &AppHandle) -> bool {
    app.get_webview_window("main")
        .and_then(|w| w.is_visible().ok())
        .unwrap_or(false)
}

fn set_toggle_label(app: &AppHandle) {
    let label = if settings_window_visible(app) {
        "Hide Agent Settings"
    } else {
        "Show Agent Settings"
    };
    if let Some(item) = TRAY_TOGGLE_ITEM.get() {
        let _ = item.set_text(label);
    }
}

fn install_tray(handle: AppHandle) -> Result<(), String> {
    let icons = TRAY_ICONS
        .get()
        .cloned()
        .ok_or_else(|| "tray icons not initialised".to_string())?;

    let initial_toggle_label = if settings_window_visible(&handle) {
        "Hide Agent Settings"
    } else {
        "Show Agent Settings"
    };
    let toggle_i = MenuItem::with_id(
        &handle,
        "toggle_settings",
        initial_toggle_label,
        true,
        None::<&str>,
    )
    .map_err(|e| e.to_string())?;
    let _ = TRAY_TOGGLE_ITEM.set(toggle_i.clone());

    let menu = MenuBuilder::new(&handle)
        .item(&toggle_i)
        .build()
        .map_err(|e| e.to_string())?;

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(icons.bad.clone())
        .tooltip("Sentinel Agent — Disconnected")
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(move |app, event| {
            if event.id().as_ref() == "toggle_settings" {
                if settings_window_visible(app) {
                    hide_settings_window(app);
                } else {
                    show_settings_window(app.clone());
                }
                set_toggle_label(app);
            }
        })
        .build(&handle)
        .map_err(|e| e.to_string())?;

    Ok(())
}

fn ensure_tray_matches_config(app: &AppHandle) {
    let enabled = app
        .state::<StoredConfig>()
        .0
        .lock()
        .map(|c| c.tray_icon_enabled)
        .unwrap_or(true);

    if enabled {
        if app.tray_by_id(TRAY_ID).is_none() {
            if let Err(e) = install_tray(app.clone()) {
                warn!("Failed to install tray icon: {e}");
            }
        } else if let Some(tray) = app.tray_by_id(TRAY_ID) {
            let _ = tray.set_visible(true);
        }
        set_toggle_label(app);
    } else if let Some(tray) = app.tray_by_id(TRAY_ID) {
        let _ = tray.set_visible(false);
    }
}

fn start_tray_status_watcher(app: AppHandle) {
    // Efficiency: poll at a low frequency and only update when status changes.
    // Agent connection state changes relatively rarely, so this is effectively idle.
    tauri::async_runtime::spawn(async move {
        use tokio::time::{sleep, Duration};

        let mut last_status = AgentStatus::Disconnected;
        let mut last_tooltip = String::new();
        let mut last_kind = "";
        let mut last_visible = settings_window_visible(&app);
        let mut last_tray_enabled = app
            .state::<StoredConfig>()
            .0
            .lock()
            .map(|c| c.tray_icon_enabled)
            .unwrap_or(true);

        loop {
            let tray_enabled = app
                .state::<StoredConfig>()
                .0
                .lock()
                .map(|c| c.tray_icon_enabled)
                .unwrap_or(true);

            if tray_enabled != last_tray_enabled {
                ensure_tray_matches_config(&app);
                last_tray_enabled = tray_enabled;
            }

            let status = app
                .state::<SharedStatus>()
                .0
                .lock()
                .map(|s| s.clone())
                .unwrap_or(AgentStatus::Error("status lock poisoned".into()));

            let visible_now = settings_window_visible(&app);
            if visible_now != last_visible {
                set_toggle_label(&app);
                last_visible = visible_now;
            }

            if status != last_status {
                let (tooltip, kind) = status_to_tray_payload(&status);

                // Update tooltip.
                if tooltip != last_tooltip {
                    if let Some(tray) = app.tray_by_id(TRAY_ID) {
                        let _ = tray.set_tooltip(Some(tooltip.clone()));
                    }
                    last_tooltip = tooltip;
                }

                // Update icon only when the "kind" changes.
                if kind != last_kind {
                    if let Some(tray) = app.tray_by_id(TRAY_ID) {
                        let icons = TRAY_ICONS.get().cloned();
                        if let Some(icons) = icons {
                            let icon = match kind {
                                "ok" => icons.ok,
                                "busy" => icons.busy,
                                _ => icons.bad,
                            };
                            let _ = tray.set_icon(Some(icon));
                        }
                    }
                    last_kind = kind;
                }

                last_status = status;
            }

            sleep(Duration::from_millis(900)).await;
        }
    });
}

// ─── Shared state wrappers ─────────────────────────────────────────────────────

/// Watch sender — agent loop listens on the receiver end.
pub struct SharedConfigTx(pub tokio::sync::watch::Sender<Option<Config>>);

/// Latest saved config — shared with the background agent thread so server-pushed
/// UI password updates stay in sync with the settings window.
pub struct StoredConfig(pub Arc<Mutex<Config>>);

/// Agent connection status — written by the agent loop, read by `get_status`.
pub struct SharedStatus(pub Arc<Mutex<AgentStatus>>);

// ─── IPC command payloads ──────────────────────────────────────────────────────

#[derive(serde::Serialize)]
pub struct StatusResponse {
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Extended save payload: normal Config fields + an optional new plaintext password.
#[derive(serde::Deserialize)]
pub struct SaveConfigPayload {
    pub server_url: String,
    pub agent_name: String,
    pub agent_token: String,
    #[serde(default)]
    pub install_id: String,
    pub ui_password_hash: String,
    #[serde(default = "default_auto_update_enabled")]
    pub auto_update_enabled: bool,
    #[serde(default = "default_tray_icon_enabled")]
    pub tray_icon_enabled: bool,
    /// Present only when the user is changing the UI password.
    pub new_password: Option<String>,
}

const fn default_auto_update_enabled() -> bool {
    false
}

const fn default_tray_icon_enabled() -> bool {
    true
}

/// Quick pairing: request approval, then receive a per-device token.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdoptEnrollmentPayload {
    pub server_url: String,
    pub enrollment_code: String,
    #[serde(default)]
    pub agent_name: Option<String>,
}

#[derive(serde::Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct DiscoverMdnsOpts {
    #[serde(default)]
    pub timeout_ms: Option<u64>,
}

#[derive(serde::Serialize)]
pub struct ManualUpdateCheckResponse {
    pub update_available: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub published_version: Option<String>,
    pub running_version: String,
}

#[derive(serde::Serialize)]
pub struct ManualApplyUpdateResponse {
    pub outcome: String,
}

pub use crate::log_sources::LogSourceDesc;

// ─── Tauri commands ────────────────────────────────────────────────────────────

#[tauri::command]
fn list_log_sources() -> Vec<LogSourceDesc> {
    crate::log_sources::list_log_sources()
}

#[tauri::command]
fn read_log_file_tail(kind: String, max_kb: Option<u32>) -> Result<String, String> {
    let max_bytes = (max_kb.unwrap_or(512).min(2048) as usize).saturating_mul(1024);
    let path = crate::log_sources::resolve_log_kind(kind.trim())?;
    crate::log_sources::read_log_tail_display(&path, max_bytes)
}

/// Truncate the specified log file to zero bytes.
/// Because the logger opens the file with `O_APPEND`, the next write will
/// automatically seek to position 0 (the new EOF), so no null-byte gap appears.
#[tauri::command]
async fn clear_log_file(kind: String) -> Result<(), String> {
    let path = crate::log_sources::resolve_log_kind(kind.trim())?;
    let res = std::fs::OpenOptions::new()
        .write(true)
        .truncate(true)
        .open(&path)
        .map(|_| ());

    match res {
        Ok(()) => Ok(()),
        Err(e) => {
            // If a log is owned by the LocalSystem service (e.g. `service.log`), the
            // user-session settings UI may not have permission to truncate it.
            // Fall back to asking the service over the existing updater pipe.
            #[cfg(target_os = "windows")]
            {
                if e.kind() == std::io::ErrorKind::PermissionDenied {
                    crate::updater_client::clear_log_file_via_service(kind.trim())
                        .await
                        .map_err(|e| format!("Could not clear log (via service): {e:#}"))?;
                    return Ok(());
                }
            }
            Err(format!("Could not clear log: {e}"))
        }
    }
}

/// Open the log file's parent folder in the OS file manager.
/// On Windows, uses `explorer /select,<path>` to also highlight the file.
#[tauri::command]
fn open_log_location(kind: String) -> Result<(), String> {
    let path = crate::log_sources::resolve_log_kind(kind.trim())?;

    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        let select_arg = format!("/select,{}", path.display());
        std::process::Command::new("explorer.exe")
            .creation_flags(CREATE_NO_WINDOW)
            .arg(&select_arg)
            .spawn()
            .map(|_| ())
            .map_err(|e| format!("Could not open Explorer: {e}"))
    }
    #[cfg(not(target_os = "windows"))]
    {
        let folder = path.parent().unwrap_or(&path);
        std::process::Command::new("open")
            .arg(folder)
            .spawn()
            .map(|_| ())
            .map_err(|e| format!("Could not open folder: {e}"))
    }
}

#[tauri::command]
fn get_config(stored: State<StoredConfig>) -> Config {
    stored.0.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

#[tauri::command]
fn save_config(
    config: SaveConfigPayload,
    stored: State<StoredConfig>,
    config_tx: State<SharedConfigTx>,
    app: AppHandle,
) -> Result<(), String> {
    // Lock once to avoid deadlocks (multiple lock() calls in one expression can re-lock).
    let (
        preserve_ui_hash,
        preserve_internet_blocked,
        preserve_internet_block_rules,
        preserve_app_block_rules,
    ) = {
        let cur = stored.0.lock().unwrap_or_else(|e| e.into_inner());
        (
            cur.ui_password_hash.clone(),
            cur.internet_blocked,
            cur.internet_block_rules.clone(),
            cur.app_block_rules.clone(),
        )
    };

    let ui_hash = if let Some(ref pw) = config.new_password {
        if pw.is_empty() {
            // Empty new_password → keep existing hash
            preserve_ui_hash
        } else {
            crate::config::hash_ui_password_argon2(pw)?
        }
    } else {
        config.ui_password_hash.clone()
    };

    let new_cfg = Config {
        server_url: config.server_url.trim().to_string(),
        agent_name: config.agent_name.trim().to_string(),
        agent_token: config.agent_token,
        install_id: config.install_id,
        ui_password_hash: ui_hash,
        auto_update_enabled: config.auto_update_enabled,
        tray_icon_enabled: config.tray_icon_enabled,
        // Preserve the server-managed internet block state; the settings UI does not touch it.
        internet_blocked: preserve_internet_blocked,
        // Preserve internet block rules; managed remotely.
        internet_block_rules: preserve_internet_block_rules,
        // Preserve app block rules; managed remotely.
        app_block_rules: preserve_app_block_rules,
    };

    crate::config::save_config(&new_cfg).map_err(|e| e.to_string())?;

    // Hot-reload: wake the agent loop with the new config.
    let _ = config_tx.0.send(Some(new_cfg.clone()));
    tauri::async_runtime::spawn(async {
        crate::ipc::notify_config_changed_best_effort().await;
    });

    // Update the in-memory copy so subsequent get_config() reads are fresh.
    *stored.0.lock().unwrap_or_else(|e| e.into_inner()) = new_cfg;

    // Apply tray visibility preference immediately.
    ensure_tray_matches_config(&app);

    info!("Config saved and hot-reloaded.");
    Ok(())
}

#[tauri::command]
fn get_status(status: State<SharedStatus>) -> StatusResponse {
    let s = status.0.lock().unwrap_or_else(|e| e.into_inner()).clone();
    match s {
        AgentStatus::Connected => StatusResponse {
            status: "Connected".into(),
            message: None,
        },
        AgentStatus::Connecting => StatusResponse {
            status: "Connecting".into(),
            message: None,
        },
        AgentStatus::Disconnected => StatusResponse {
            status: "Disconnected".into(),
            message: None,
        },
        AgentStatus::Error(msg) => StatusResponse {
            status: "Error".into(),
            message: Some(msg),
        },
    }
}

#[tauri::command]
fn get_app_version(app: AppHandle) -> String {
    app.package_info().version.to_string()
}

#[tauri::command]
fn has_ui_password(stored: State<StoredConfig>) -> bool {
    let cfg = stored.0.lock().unwrap_or_else(|e| e.into_inner());
    let h = cfg.ui_password_hash.as_str();
    !h.is_empty() && h.starts_with("$argon2")
}

#[tauri::command]
fn verify_ui_password(password: String, stored: State<StoredConfig>) -> Result<(), String> {
    let cfg = stored.0.lock().unwrap_or_else(|e| e.into_inner());
    let expected = cfg.ui_password_hash.as_str();
    if expected.is_empty() {
        // No lock configured.
        LAST_UI_AUTH_OK_AT
            .get_or_init(|| AtomicI64::new(0))
            .store(crate::unix_timestamp_secs() as i64, Ordering::Relaxed);
        return Ok(());
    }
    let Ok(parsed) = PasswordHash::new(expected) else {
        return Err("Invalid stored password hash".into());
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .map_err(|_| "Wrong password".to_string())?;
    LAST_UI_AUTH_OK_AT
        .get_or_init(|| AtomicI64::new(0))
        .store(crate::unix_timestamp_secs() as i64, Ordering::Relaxed);
    Ok(())
}

#[tauri::command]
fn hide_window(app: AppHandle) {
    if let Some(win) = app.get_webview_window("main") {
        let _ = win.emit("lock_ui", ());
        // Fully destroy the webview to release WebView2 memory.
        // We'll recreate it on demand via Ctrl+Shift+F12 (or first-run).
        let _ = win.destroy();
    }
}

#[tauri::command]
fn exit_agent(stored: State<StoredConfig>) -> Result<(), String> {
    // If a UI password is set, require a recent successful verification.
    let cfg = stored.0.lock().unwrap_or_else(|e| e.into_inner());
    let expected = cfg.ui_password_hash.as_str();
    let has_pw = !expected.is_empty() && expected.starts_with("$argon2");
    drop(cfg);

    if has_pw {
        let now = crate::unix_timestamp_secs() as i64;
        let last = LAST_UI_AUTH_OK_AT
            .get_or_init(|| AtomicI64::new(0))
            .load(Ordering::Relaxed);
        // Tight window: quitting is sensitive; require a fresh auth.
        if last <= 0 || (now - last).abs() > 60 {
            return Err("Authentication required to exit".into());
        }
    }
    std::process::exit(0);
}

#[cfg(target_os = "windows")]
#[tauri::command]
async fn check_manual_update() -> Result<ManualUpdateCheckResponse, String> {
    let r = crate::updater_client::check_manual_update_available()
        .await
        .map_err(|e| format!("{e:#}"))?;
    Ok(ManualUpdateCheckResponse {
        update_available: r.update_available,
        published_version: r.published_version,
        running_version: r.running_version,
    })
}

#[cfg(target_os = "windows")]
#[tauri::command]
async fn apply_manual_update() -> Result<ManualApplyUpdateResponse, String> {
    use crate::updater_client::{exit_for_update, update_via_service, UpdateViaServiceOutcome};
    use std::time::Duration;
    match update_via_service().await {
        Ok(UpdateViaServiceOutcome::UpToDate) => Ok(ManualApplyUpdateResponse {
            outcome: "up_to_date".into(),
        }),
        Ok(UpdateViaServiceOutcome::InstallStarted) => {
            crate::config::request_reopen_settings_ui_after_restart();
            tauri::async_runtime::spawn(async move {
                tokio::time::sleep(Duration::from_millis(300)).await;
                exit_for_update();
            });
            Ok(ManualApplyUpdateResponse {
                outcome: "install_started".into(),
            })
        }
        Err(e) => Err(format!("{e:#}")),
    }
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
async fn check_manual_update() -> Result<ManualUpdateCheckResponse, String> {
    Err("Sentinel MSI update checks are only supported on Windows.".into())
}

#[cfg(not(target_os = "windows"))]
#[tauri::command]
async fn apply_manual_update() -> Result<ManualApplyUpdateResponse, String> {
    Err("Sentinel MSI installs from the settings UI are only supported on Windows.".into())
}

#[tauri::command]
fn discover_sentinel_mdns_servers(
    opts: DiscoverMdnsOpts,
) -> Vec<crate::mdns_discover::DiscoveredServer> {
    #[cfg(target_os = "windows")]
    {
        crate::mdns_discover::discover_sentinel_servers(opts.timeout_ms.unwrap_or(3500))
    }
    #[cfg(not(target_os = "windows"))]
    {
        Vec::new()
    }
}

#[tauri::command]
async fn adopt_with_enrollment_code(
    payload: AdoptEnrollmentPayload,
    stored: State<'_, StoredConfig>,
    config_tx: State<'_, SharedConfigTx>,
) -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        let name = payload
            .agent_name
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(str::to_string)
            .unwrap_or_else(|| std::env::var("COMPUTERNAME").unwrap_or_else(|_| "agent".into()));
        let cfg = crate::enrollment::adopt_with_enrollment(
            payload.server_url.trim(),
            payload.enrollment_code.trim(),
            &name,
        )
        .await
        .map_err(|e| e.to_string())?;
        *stored.0.lock().unwrap_or_else(|e| e.into_inner()) = cfg.clone();
        let watch = if cfg.server_url.is_empty() {
            None
        } else {
            Some(cfg)
        };
        let _ = config_tx.0.send(watch);
        crate::ipc::notify_config_changed_best_effort().await;
        info!("Adopted via pairing code; config hot-reloaded.");
        Ok(())
    }
    #[cfg(not(target_os = "windows"))]
    {
        let _ = (stored, config_tx, payload);
        Err("Enrollment is only supported on Windows.".into())
    }
}

// ─── Public entry point ────────────────────────────────────────────────────────

/// Build and run the Tauri event loop.  **Blocks the calling thread forever**
/// (or until the user clicks "Exit Agent").
pub fn run_tauri(
    initial_config: Config,
    config_tx: tokio::sync::watch::Sender<Option<Config>>,
    shared_cfg: Arc<Mutex<Config>>,
    agent_status: Arc<Mutex<AgentStatus>>,
    show_on_startup: bool,
) {
    let app = tauri::Builder::default()
        // Ensure only one instance of the agent settings app runs.
        // If a second instance is launched, we focus/show the existing window
        // and the new instance exits automatically via the plugin.
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(win) = app.get_webview_window("main") {
                let _ = win.show();
                let _ = win.set_focus();
            }
        }))
        // ── Plugins ─────────────────────────────────────────────────────────
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        // ── Shared state ────────────────────────────────────────────────────
        .manage(SharedConfigTx(config_tx))
        .manage(StoredConfig(shared_cfg))
        .manage(SharedStatus(agent_status))
        // ── Commands ────────────────────────────────────────────────────────
        .invoke_handler(tauri::generate_handler![
            get_config,
            save_config,
            get_status,
            get_app_version,
            has_ui_password,
            verify_ui_password,
            hide_window,
            exit_agent,
            check_manual_update,
            apply_manual_update,
            discover_sentinel_mdns_servers,
            adopt_with_enrollment_code,
            list_log_sources,
            read_log_file_tail,
            clear_log_file,
            open_log_location,
        ])
        // ── Setup ────────────────────────────────────────────────────────────
        .setup(move |app| {
            let _ = APP_HANDLE.set(app.handle().clone());

            // Precompute tray icons once (cheap and avoids any runtime decoding on updates).
            if TRAY_ICONS.get().is_none() {
                match build_tray_icons() {
                    Ok(i) => {
                        let _ = TRAY_ICONS.set(i);
                    }
                    Err(e) => {
                        warn!("Failed to build tray icons: {e}");
                    }
                }
            }

            // Install the tray if enabled. Even if it fails, keep the agent functional.
            let enabled = app
                .state::<StoredConfig>()
                .0
                .lock()
                .map(|c| c.tray_icon_enabled)
                .unwrap_or(true);
            if enabled {
                if let Err(e) = install_tray(app.handle().clone()) {
                    warn!("Failed to install tray icon: {e}");
                }
            }
            start_tray_status_watcher(app.handle().clone());

            // When `auto_update_enabled` is true (default off): check shortly after app startup,
            // then every 6 hours. Windows uses `update_via_service` + MSI; other OSes use Tauri updater.
            const AUTO_UPDATE_STARTUP_DELAY_SECS: u64 = 45;
            const AUTO_UPDATE_INTERVAL_SECS: u64 = 60 * 60 * 6;

            #[cfg(target_os = "windows")]
            {
                use crate::updater_client::{update_via_service, UpdateViaServiceOutcome};
                let stored_cfg = app.state::<StoredConfig>().0.clone();
                tauri::async_runtime::spawn(async move {
                    tokio::time::sleep(std::time::Duration::from_secs(
                        AUTO_UPDATE_STARTUP_DELAY_SECS,
                    ))
                    .await;
                    loop {
                        let enabled = stored_cfg
                            .lock()
                            .map(|c| c.auto_update_enabled)
                            .unwrap_or(false);
                        if enabled {
                            match update_via_service().await {
                                Ok(UpdateViaServiceOutcome::InstallStarted) => {
                                    tokio::time::sleep(std::time::Duration::from_millis(400)).await;
                                    crate::updater_client::exit_for_update();
                                }
                                Ok(UpdateViaServiceOutcome::UpToDate) => {}
                                Err(e) => warn!("Auto-update (Windows): {e:#}"),
                            }
                        }
                        tokio::time::sleep(std::time::Duration::from_secs(
                            AUTO_UPDATE_INTERVAL_SECS,
                        ))
                        .await;
                    }
                });
            }

            #[cfg(not(target_os = "windows"))]
            {
                let handle_for_updates = app.handle().clone();
                let stored_cfg = app.state::<StoredConfig>().0.clone();
                tauri::async_runtime::spawn(async move {
                    let result: Result<(), String> = async {
                        tokio::time::sleep(std::time::Duration::from_secs(
                            AUTO_UPDATE_STARTUP_DELAY_SECS,
                        ))
                        .await;
                        loop {
                            let enabled = stored_cfg
                                .lock()
                                .map(|c| c.auto_update_enabled)
                                .unwrap_or(false);
                            if enabled {
                                let update = handle_for_updates
                                    .updater_builder()
                                    .build()
                                    .map_err(|e| e.to_string())?
                                    .check()
                                    .await
                                    .map_err(|e| e.to_string())?;

                                if let Some(update) = update {
                                    info!(
                                        "Update available: {} ({:?})",
                                        update.version, update.date
                                    );
                                    update
                                        .download_and_install(
                                            |_downloaded, _content_length| {},
                                            || {},
                                        )
                                        .await
                                        .map_err(|e| format!("{e:?}"))?;
                                }
                            }
                            tokio::time::sleep(std::time::Duration::from_secs(
                                AUTO_UPDATE_INTERVAL_SECS,
                            ))
                            .await;
                        }
                    }
                    .await;

                    if let Err(e) = result {
                        error!("Updater error: {e}");
                    }
                });
            }

            let Some(win) = app.get_webview_window("main") else {
                // Surface as a setup error instead of panicking on the UI thread (panic = "abort"
                // would take down the whole agent process).
                return Err("main window missing".into());
            };

            // Show on first run or explicit flag
            let is_first_run = initial_config.server_url.is_empty();
            if is_first_run || show_on_startup {
                let _ = win.show();
                let _ = win.set_focus();
            } else {
                // Not needed right now: destroy the webview so WebView2 doesn't sit
                // around consuming memory in the background.
                let _ = win.destroy();
            }

            // Register Ctrl+Shift+F12 global shortcut
            let app_handle = app.handle().clone();
            let shortcut = Shortcut::new(Some(Modifiers::CONTROL | Modifiers::SHIFT), Code::F12);

            app.global_shortcut()
                .on_shortcut(shortcut, move |_app_handle, _shortcut, event| {
                    if event.state() == ShortcutState::Pressed {
                        // Creating a window in an event handler can deadlock on Windows (WebView2).
                        // Spawn a thread (Tauri docs recommendation).
                        let handle = app_handle.clone();
                        std::thread::spawn(move || {
                            if let Some(w) = handle.get_webview_window("main") {
                                let visible = w.is_visible().unwrap_or(false);
                                if visible {
                                    let _ = w.emit("lock_ui", ());
                                    let _ = w.destroy();
                                } else {
                                    let _ = w.show();
                                    let _ = w.set_focus();
                                }
                                return;
                            }

                            // Recreate from config template (keeps size/min size/decorations consistent).
                            let cfg = handle
                                .config()
                                .app
                                .windows
                                .iter()
                                .find(|w| w.label == "main")
                                .or_else(|| handle.config().app.windows.first())
                                .cloned();

                            let Some(conf) = cfg else { return };
                            let _ = tauri::WebviewWindowBuilder::from_config(&handle, &conf)
                                .and_then(tauri::WebviewWindowBuilder::build);

                            if let Some(w) = handle.get_webview_window("main") {
                                let _ = w.show();
                                let _ = w.set_focus();
                            }
                        });
                    }
                })
                .unwrap_or_else(|e| {
                    error!("Failed to register global shortcut Ctrl+Shift+F12: {e}");
                });

            info!("Tauri settings window initialised (show_on_startup={show_on_startup}).");
            Ok(())
        })
        // ── Window close → hide instead of quit ──────────────────────────────
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.emit("lock_ui", ());
                // Destroy to reclaim WebView2 memory; recreate on demand.
                if let Some(w) = window.app_handle().get_webview_window(window.label()) {
                    let _ = w.destroy();
                }
            }
        })
        .build(tauri::generate_context!())
        .unwrap_or_else(|e| {
            error!("Tauri runtime error: {e}");
            // Keep process alive so the agent background thread continues.
            loop {
                std::thread::sleep(std::time::Duration::from_secs(60));
            }
        });

    // Critical: if we destroy the only window, Tauri may try to exit.
    // Prevent exit so the background agent keeps running; `exit_agent()` handles real shutdown.
    app.run(|_app_handle, event| {
        if let tauri::RunEvent::ExitRequested { api, .. } = event {
            api.prevent_exit();
        }
    });
}

#[cfg(not(target_os = "windows"))]
pub fn trigger_update_now() {
    let Some(handle) = APP_HANDLE.get().cloned() else {
        // Headless mode (no UI / no Tauri event loop).
        return;
    };
    tauri::async_runtime::spawn(async move {
        let result: Result<(), String> = async {
            let update = handle
                .updater_builder()
                .build()
                .map_err(|e| e.to_string())?
                .check()
                .await
                .map_err(|e| e.to_string())?;

            let Some(update) = update else {
                return Ok(());
            };
            info!("Update-now: installing {}", update.version);
            update
                .download_and_install(|_downloaded, _content_length| {}, || {})
                .await
                .map_err(|e| format!("{e:?}"))?;
            Ok(())
        }
        .await;

        if let Err(e) = result {
            error!("Update-now failed: {e}");
        }
    });
}
